### ISSUE TITLE
Colorfy crashes when no arguments are given

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/colorfy#3]
Instead, Colorfy should exit gracefully, perhaps reminding the user of its usage by printing the `colorfy -h` output.

**Comment by SebastianSemper** [comment]
Agreed, proceed.

**Comment by SebastianSemper** [comment]
I added `required=True` to the input and output arguments. Now if these arguments are not specified, colorfy prints that these two are required and a condensed help text.
